# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 03-Packages.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----install-managers, eval=FALSE-------------------------
# install.packages("BiocManager")
# install.packages("devtools")


## ----install-all-packages, eval=FALSE---------------------
# # Package managers (if not already installed)
# if(!require(BiocManager)) install.packages("BiocManager")
# if(!require(devtools)) install.packages("devtools")
# 
# # Core programming utilities
# if(!require(rlang)) install.packages("rlang")         # R language utilities and C++ integration
# 
# # Core cytometry packages - read FCS files and create cytometry plots
# if(!require(flowCore)) BiocManager::install("flowCore")
# if(!require(ggcyto)) BiocManager::install("ggcyto")
# 
# # Advanced cytometry analysis - clustering and population discovery
# if(!require(FlowSOM)) BiocManager::install("FlowSOM")
# if(!require(flowCut)) BiocManager::install("flowCut")
# if(!require(flowWorkspace)) BiocManager::install("flowWorkspace") # GatingSet functions used in the Gating chapter
# if(!require(openCyto)) BiocManager::install("openCyto")           # estimateMedianLogicle(), used in the Transformation chapter
# 
# # Dimensionality reduction for cytometry
# if(!require(uwot)) install.packages("uwot")           # UMAP implementation
# if(!require(Rtsne)) install.packages("Rtsne")         # t-SNE implementation
# if(!require(ggh4x)) install.packages("ggh4x")         # facet_nested_wrap(), nested per-sample panels in the Dimensionality Reduction chapter
# if(!require(dbscan)) install.packages("dbscan")       # Density clustering, used to gate regions on a UMAP
# if(!require(ggforce)) install.packages("ggforce")     # geom_mark_hull(), draws those gates as outlines rather than boxes
# 
# # Data manipulation and general visualisation
# if(!require(tidyverse)) install.packages("tidyverse")  # Data wrangling toolkit
# if(!require(tidyr)) install.packages("tidyr")          # pivot_longer(), reshaping wide tables to long. Ships inside tidyverse, listed separately because several chapters load it directly
# if(!require(cowplot)) install.packages("cowplot")     # Multi-panel figures
# if(!require(ggtext)) install.packages("ggtext")       # Enhanced text formatting
# if(!require(ggridges)) install.packages("ggridges")   # Ridge/density plots for distributions
# 
# # Colour and visualisation utilities
# if(!require(RColorBrewer)) install.packages("RColorBrewer") # Colour palettes
# if(!require(viridis)) install.packages("viridis")     # Colourblind-friendly palettes
# if(!require(colorspace)) install.packages("colorspace") # Colour manipulation
# if(!require(scales)) install.packages("scales")       # Plot scaling
# if(!require(GGally)) install.packages("GGally")       # ggpairs() NxN marker grids, used in the Channel Names chapter
# if(!require(pheatmap)) install.packages("pheatmap")   # Heatmaps, used in the Statistics chapter
# if(!require(ggrepel)) install.packages("ggrepel")     # Non-overlapping plot labels, used in the Statistics chapter
# library(grDevices) # Graphics devices; ships with base R, no installation needed
# 
# # Animation, used in the Dimensionality Reduction chapter
# if(!require(gganimate)) install.packages("gganimate") # Animates a ggplot across a variable
# if(!require(gifski)) install.packages("gifski")       # Renders the frames to a GIF. gganimate needs a renderer and will fail without one
# 
# # Statistical analysis
# if(!require(limma)) BiocManager::install("limma")     # Differential expression
# if(!require(fBasics)) install.packages("fBasics")     # Basic statistics
# 
# # File management and data handling
# if(!require(here)) install.packages("here")           # Portable file paths
# if(!require(readxl)) install.packages("readxl")       # Read Excel files
# 
# # Utilities and system integration
# if(!require(foreach)) install.packages("foreach")     # Parallel processing
# if(!require(rstudioapi)) install.packages("rstudioapi")    # RStudio integration
# 
# # Specialized cytometry data cleaning
# if(!require(premessa)) devtools::install_github("ParkerICI/premessa", force = TRUE)
# if(!require(Rphenograph)) devtools::install_github("JinmiaoChenLab/Rphenograph", force = TRUE)  # Clustering alternative to FlowSOM, used in the Clustering chapter


## ----verify-installation, eval=FALSE----------------------
# library(flowCore)
# library(ggcyto)
# library(tidyverse)
# library(here)


## ----install-via-jobs, eval=FALSE-------------------------
# if(!require(job)) install.packages("job")
# 
# job::job({
#   install.packages(c("ggplot2", "tidyverse", "devtools", "BiocManager"))
# })


## ----cran-install, eval=FALSE-----------------------------
# install.packages("packagename")


## ----bioc-manager, eval=FALSE-----------------------------
# install.packages("BiocManager")


## ----bioc-install, eval=FALSE-----------------------------
# BiocManager::install("packagename")


## ----devtools-install, eval=FALSE-------------------------
# install.packages("devtools")


## ----github-install, eval=FALSE---------------------------
# devtools::install_github("username/packagename")


## ----install-once, eval=FALSE-----------------------------
# install.packages("flowCore")


## ----load-session, eval=FALSE-----------------------------
# library(flowCore)


## ----require-vs-library, eval=FALSE-----------------------
# # Using require() - gives warning, continues running
# require(nonexistent_package)
# some_function()  # This might fail mysteriously later
# 
# # Using library() - stops immediately with clear error
# library(nonexistent_package)  # Error: package not found
# some_function()  # This line never runs


## ----check-installed, eval=FALSE--------------------------
# installed.packages()


## ----update-packages, eval=FALSE--------------------------
# update.packages()


## ----remove-package, eval=FALSE---------------------------
# remove.packages("packagename")


## ----package-info, eval=FALSE-----------------------------
# packageDescription("packagename")


## ----quick-help, eval=FALSE-------------------------------
# ?packagename


## ----vignettes, eval=FALSE--------------------------------
# browseVignettes("packagename")

