# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 04-File-Management.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----create-folders---------------------------------------
library(here)
dir.create(here("Data", "RDS"), recursive = TRUE, showWarnings = FALSE)
dir.create(here("Scripts"), showWarnings = FALSE)
dir.create(here("Figures"), showWarnings = FALSE)
dir.create(here("Tables"), showWarnings = FALSE)
dir.create(here("Outputs"), showWarnings = FALSE)


## ----check-here-------------------------------------------
here()


## ----verify-fcs-------------------------------------------
list.files(here("Data", "fcs"))


## ----getwd, eval=FALSE------------------------------------
# getwd()


## ---------------------------------------------------------
"C:/Users/YourName/Documents/Cytometry_R_Course/Data/fcs"


## ---------------------------------------------------------
"Data/fcs"


## ----eval=FALSE-------------------------------------------
# # This only works on your computer
# data <- read.csv("C:/Users/YourName/Cytometry_R_Course/Data/other/samples.csv")


## ----eval=FALSE-------------------------------------------
# # This works on anyone's computer
# data <- read.csv(here("Data", "other", "samples.csv"))


## ---------------------------------------------------------
here()                                     # Project root
here("Data")                               # Data folder
here("Data", "fcs")                 # FCS subfolder
here("Data", "fcs", "2PFANASPermLIVE.fcs")  # A specific file


## ----eval=FALSE-------------------------------------------
# dir.create(here("Scripts"))


## ----eval=FALSE-------------------------------------------
# dir.create(here("Figures"))
# dir.create(here("Tables"))


## ---------------------------------------------------------
list.dirs()


## ---------------------------------------------------------
list.files()


## ---------------------------------------------------------
list.files(here("Data", "fcs"), pattern = ".fcs$")

