# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 05-Data-Import.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages----------------------------------------
library(flowCore)
library(here)


## ----read-flowset-----------------------------------------
FLOWSET <- read.flowSet(path = here("Data", "fcs"), pattern = "\\.fcs$") # The "pattern ="\\.fcs" command ensures that the data import can take place even if there are other irrelevant files and folders present. If you don't use this ad there is an unexpected folder or file, you'lkl get an error.


## ----check-length-----------------------------------------
length(FLOWSET)


## ----check-names------------------------------------------
sampleNames(FLOWSET)


## ----check-colnames---------------------------------------
colnames(FLOWSET)


## ----check-markernames------------------------------------
markernames(FLOWSET)


## ----create-rds-folder------------------------------------
dir.create(here("Data", "RDS"), showWarnings = FALSE)


## ----save-flowset-----------------------------------------
saveRDS(FLOWSET, here("Data", "RDS", "FLOWSET.rds"))


## ----check-saved-rds--------------------------------------
file.exists(here("Data", "RDS", "FLOWSET.rds"))


## ----read-fcs-single--------------------------------------
FLOWFRAME <- read.FCS(here("Data", "fcs", "2PFANASPermLIVE.fcs"))
class(FLOWFRAME)


## ----at-symbol-demo, eval=FALSE---------------------------
# FLOWFRAME@exprs


## ----at-symbol-danger, eval=FALSE-------------------------
# FLOWFRAME@exprs <- matrix(1:10, nrow = 2)  # wrong dimensions entirely, R accepts it anyway


## ----at-symbol-safe, eval=FALSE---------------------------
# exprs(FLOWFRAME) <- matrix(1:10, nrow = 2)  # exprs() checks this against the object before allowing it


## ----single-bracket---------------------------------------
SUBSET <- FLOWSET[c(1, 3)]
class(SUBSET)
length(SUBSET)


## ----double-bracket---------------------------------------
FLOWFRAME <- FLOWSET[[1]]
class(FLOWFRAME)


## ----dollar-sign, eval=FALSE------------------------------
# SAMPLE_INFO <- pData(FLOWSET)
# SAMPLE_INFO$name


## ----check-class------------------------------------------
class(FLOWFRAME)


## ----check-nrow-------------------------------------------
nrow(FLOWFRAME) # tells you the number or rows i.e. how many events have data recorded withing hte FlowFrame
nrow(FLOWSET) # Returns "NULL" showing these types of commands expecta flowFrame, not a flowSet
fsApply(FLOWSET, nrow) # Use fsApply to use "nrow()" to every flowFrame within a flowSet


## ----check-ncol-------------------------------------------
ncol(FLOWSET[[1]])


## ----show-colnames, eval=FALSE----------------------------
# colnames(FLOWSET)


## ----show-markernames, eval=FALSE-------------------------
# markernames(FLOWSET)


## ----show-exprs-------------------------------------------
exprs(FLOWFRAME)[1:5, 1:5]


## ----show-keyword-----------------------------------------
keyword(FLOWFRAME, "FILENAME")


## ----show-all-keywords, eval=FALSE------------------------
# keyword(FLOWFRAME)


## ----get-dims---------------------------------------------
fsApply(FLOWSET, dim)


## ----get-median-------------------------------------------
fsApply(FLOWSET, each_col, median)[1:5, 1:5]


## ----subset-samples---------------------------------------
SUBSET <- FLOWSET[c(1,3,5)]
length(SUBSET)


## ----subset-channels--------------------------------------
MARKERS_ONLY <- FLOWSET[, 7:15]
ncol(MARKERS_ONLY[[1]])


## ----save-rds, eval=FALSE---------------------------------
# saveRDS(FLOWSET, here("Data", "RDS", "FLOWSET.rds"))


## ----load-rds, eval=FALSE---------------------------------
# FLOWSET <- readRDS(here("Data", "RDS", "FLOWSET.rds"))


## ----common-ops, eval=FALSE-------------------------------
# # Check what you have
# length(FLOWSET)              # Number of files
# sampleNames(FLOWSET)         # File names
# colnames(FLOWSET)            # Channel names
# markernames(FLOWSET)         # Marker annotations
# 
# # Get information
# fsApply(FLOWSET, nrow)       # Cell counts
# ncol(FLOWSET[[1]])           # Number of channels
# keyword(FLOWSET[[1]], "key") # Specific keyword
# 
# # Access data
# FLOWFRAME <- FLOWSET[[1]]    # Extract one file
# exprs(FLOWFRAME)             # Get expression matrix

