# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 06-Data-Visualisation.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-viz-primer-----------------------------
library(flowCore)
library(ggcyto)
library(here)


## ----load-data-viz----------------------------------------
FLOWSET <- readRDS(here("Data", "RDS", "FLOWSET.rds"))


## ----first-plot-------------------------------------------
autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di")


## ----plot-with-transform----------------------------------
autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di", bins = 128) +
  scale_x_flowCore_fasinh() +
  scale_y_flowCore_fasinh()


## ----plot-all-samples-------------------------------------
autoplot(FLOWSET, x = "Ir191Di", y = "Ir193Di", bins = 128) +
  scale_x_flowCore_fasinh() +
  scale_y_flowCore_fasinh()


## ----autoplot-syntax, eval=FALSE--------------------------
# autoplot(data, x = "marker1", y = "marker2")


## ----different-bins, eval=FALSE---------------------------
# autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di", bins = 64)   # Coarser
# autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di", bins = 256)  # Finer


## ----scale-types, eval=FALSE------------------------------
# scale_x_flowCore_fasinh()    # Hyperbolic arcsinh (recommended)
# scale_y_logicle()             # Logicle transform
# scale_x_log10()               # Log10 (can't handle negatives)


## ----different-markers, eval=FALSE------------------------
# autoplot(FLOWSET, x = "Pr141Di", y = "Nd142Di")


## ----check-markers, eval=FALSE----------------------------
# colnames(FLOWSET)


## ----one-sample-plot, eval=FALSE--------------------------
# autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di")


## ----all-samples-plot, eval=FALSE-------------------------
# autoplot(FLOWSET, x = "Ir191Di", y = "Ir193Di")


## ----facet-layout, eval=FALSE-----------------------------
# autoplot(FLOWSET, x = "Ir191Di", y = "Ir193Di") +
#   facet_wrap(~ name, ncol = 3)  # 3 columns


## ----ggcyto-example, eval=FALSE---------------------------
# ggcyto(FLOWSET, aes(x = "Ir191Di", y = "Ir193Di")) +
#   geom_hex(bins = 128) +
#   scale_x_flowCore_fasinh() +
#   scale_y_flowCore_fasinh() +
#   facet_wrap(~ name)


## ----hex-plot, eval=FALSE---------------------------------
# ggcyto(FLOWSET[[1]], aes(x = "Ir191Di", y = "Ir193Di")) +
#   geom_hex(bins = 128)


## ----point-plot, eval=FALSE-------------------------------
# ggcyto(FLOWSET[[1]], aes(x = "Ir191Di", y = "Ir193Di")) +
#   geom_point(size = 0.5, alpha = 0.3)


## ----density-plot, eval=FALSE-----------------------------
# ggcyto(FLOWSET[[1]], aes(x = "Ir191Di", y = "Ir193Di")) +
#   geom_density2d()


## ----histogram, eval=FALSE--------------------------------
# autoplot(FLOWSET, "Pr141Di") +
#   scale_x_flowCore_fasinh()


## ----overlay-histogram, eval=FALSE------------------------
# library(ggcyto)
# ggplot(FLOWSET,aes(x = Pr141Di,colour = factor(name),group = factor(name))) +
#   geom_freqpoly(aes(y = after_stat(count / max(count)))) +
#   scale_x_flowCore_fasinh()
# 


## ----custom-colors, eval=FALSE----------------------------
# autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di", bins = 128) +
#   scale_fill_viridis_c()


## ----add-title, eval=FALSE--------------------------------
# autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di") +
#   labs(title = "DNA Markers",
#        subtitle = "Sample 1",
#        x = "DNA (Ir191)",
#        y = "DNA (Ir193)")


## ----apply-theme, eval=FALSE------------------------------
# autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di") +
#   theme_minimal()


## ----save-plot, eval=FALSE--------------------------------
# ggsave(here("Figures", "dna_plot.png"), width = 8, height = 6)


## ----save-specific, eval=FALSE----------------------------
# p <- autoplot(FLOWSET, x = "Ir191Di", y = "Ir193Di")
# p
# 
# ggsave(here("Figures", "dna_all_samples.png"), plot = p, width = 12, height = 8)


## ----overlay-two, eval=FALSE------------------------------
# ggplot(
#   FLOWSET[c(1, 2)],
#   aes(
#     x = Ir191Di,
#     y = Ir193Di,
#     colour = factor(name)
#   )
# ) +
#   geom_density_2d() +
#   scale_x_flowCore_fasinh() +
#   scale_y_flowCore_fasinh()


## ----complex-plot, eval=FALSE-----------------------------
# ggcyto(FLOWSET[[1]], aes(x = "Ir191Di", y = "Ir193Di")) +
#   geom_hex(bins = 128) +
#   scale_x_flowCore_fasinh() +
#   scale_y_flowCore_fasinh() +
#   scale_fill_viridis_c(option = "plasma") +
#   labs(title = "DNA Markers", x = "DNA 1 (Ir191)", y = "DNA 2 (Ir193)") +
#   theme_minimal() +
#   theme(legend.position = "right")


## ----check-all-markers, eval=FALSE------------------------
# # Plot all markers
# autoplot(FLOWSET[[1]])


## ----compare-processing, eval=FALSE-----------------------
# p1 <- autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di") + labs(title = "Untransformed")
# p2 <- autoplot(FLOWSET[[1]], x = "Ir191Di", y = "Ir193Di", bins = 128) +
#   scale_x_flowCore_fasinh() +
#   scale_y_flowCore_fasinh() +
#   labs(title = "Transformed")
# 
# library(cowplot)
# plot_grid(as.ggplot(p1), as.ggplot(p2), ncol = 2)


## ----dna-viability, eval=FALSE----------------------------
# autoplot(FLOWSET, x = "Ir191Di", y = "Pr141Di", bins = 128) +
#   scale_x_flowCore_fasinh() +
#   scale_y_flowCore_fasinh()


## ----size-params, eval=FALSE------------------------------
# autoplot(FLOWSET, x = "Event_length", y = "Width", bins = 128)


## ----marker-expression, eval=FALSE------------------------
# autoplot(FLOWSET, x = "Sm149Di", y = "Yb172Di", bins = 128) +
#   scale_x_flowCore_fasinh() +
#   scale_y_flowCore_fasinh()

