# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 07-Data-Cleaning-1-Gating-Data.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----gating-packages, warning=FALSE, message=FALSE--------
# I expect you have these installed by now but if not you can install them with the following code;
# install.packages("here") etc. remember, for install.packages() we have to "quote" the package name
library(here)
library(tidyverse)
library(ggcyto)
library(flowCore)
library(flowWorkspace)


## ----load-data, warning=FALSE-----------------------------
FLOWSET <- readRDS(here("Data", "RDS", "FLOWSET.rds"))


## ----Gating, warning=FALSE--------------------------------
Gates <- GatingSet(FLOWSET) # A GatingSet is a collection of gates


## ----GetNodes, warning=FALSE------------------------------
gs_get_pop_paths(Gates) # returns the gates in a GatingSet i.e. it tells you which gates are a part of the GatingSet


## ----Change root Node, eval=FALSE, warning=FALSE----------
# Demo_Gates <- GatingSet(FLOWSET) # a disposable copy, just for this demonstration, so the real Gates object is never touched
# gs_pop_set_name(Demo_Gates, "root", "ungated") # We'll change the name of the root node to ungated
# gs_get_pop_paths(Demo_Gates) # Check the outcome is as expected


## ----Messing with root does not work, eval=FALSE, warning=FALSE----
# R_demo <- rectangleGate(filterId = "demo_gate", "Ir191Di" = c(1000, 10000), "Ce140Di" = c(0, 10)) # a throwaway gate, just for this demonstration
# gs_pop_add(Demo_Gates, R_demo, parent = "ungated")
# gs_get_pop_paths(Demo_Gates) # Check the outcome is as expected
# gs_pop_get_count_fast(Demo_Gates) # This line is the one that actually errors: flowWorkspace expects a node literally named "root" to exist somewhere in the tree, and renaming it broke that


## ----Plotting start state, warning=FALSE------------------
autoplot(FLOWSET, x = "Ir191Di", y = "Ce140Di") # We'll use autoplot() from the ggcyto package to visualise the data. The DNA intercalator Iridium 191 and the QC bead marker Cesium 140 are the parameters we'll use to gate out the QC beads and debris


## ----Plotting start state with arcsinh, warning=FALSE-----
autoplot(FLOWSET, x = "Ir191Di", y = "Ce140Di") + # We'll use autoplot from the ggcyto package to visualise the data
  scale_y_flowCore_fasinh() + # We'll use the flowCore package to transform the visualisation with hyperbolic arcsin for y
  scale_x_flowCore_fasinh()# We'll use the flowCore package to transform the visualisation with hyperbolic arcsin for x


## ----Plotting start state with arcsinh and bins128, warning=FALSE----
autoplot(FLOWSET, x = "Ir191Di", y = "Ce140Di", bins = 128) + # We'll use autoplot from the ggcyto package to visualise the data
  scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()


## ----Setting up our first gate, warning=FALSE-------------
# We'll set up a gate to filter out the QC Beads and debris from the cell populations
# The QC beads are 140Ce positive and the cells are Ir191 and Ir193 Positive
# First we create a rectangular gate, give it a name, choose the parameters and set the co-ordinates of the 4 corners of the gate

R1 <- rectangleGate(filterId="Non-Beads,Non-debris",
"Ir191Di"=c(1000, 10000), "Ce140Di"=c(0, 10))

# Next we set the hierarchy of the gate by choosing the parent gate
if ("/Non-Beads,Non-debris" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "Non-Beads,Non-debris") # remove any leftover gate from a previous run of this chunk before re-adding
gs_pop_add(Gates, R1, parent = "root")
# Next we recompute the gates to make sure the new gate is included in the analysis
gs_pop_get_count_fast(Gates)

# After that we can get the stats for the gate we've just set up; in this case we'll check the percentages of the cells that are not beads or debris
gs_pop_get_stats(Gates, "Non-Beads,Non-debris", type = "percent")

# Finally we can check the hierarchy of the gates, recompute them to make sure the hierarchy is up to data....
gs_get_pop_paths(Gates)
recompute(Gates)

# ... before visualising them
autoplot(FLOWSET, x = "Ir191Di", y = "Ce140Di") +
  scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()

autoplot(Gates, "Non-Beads,Non-debris", bins = 128) +
 scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()


## ----Adjust our gates, warning=FALSE----------------------
if ("/Non-Beads,Non-debris" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "Non-Beads,Non-debris") # remove any leftover gate from a previous run of this chunk before re-adding
R1 <- rectangleGate(filterId="Non-Beads,Non-debris", # Add back the gate with the new parameters
"Ir191Di"=c(100, 20000), "Ce140Di"=c(-10, 10)) # Ce140Di reverted to 10 (the original, never-flagged-as-broken upper bound); real data only goes up to ~13.3, so 100 was excluding nothing

gs_pop_add(Gates, R1, parent = "root")
gs_pop_get_count_fast(Gates)
gs_get_pop_paths(Gates)
recompute(Gates)

autoplot(Gates, "Non-Beads,Non-debris") +
 scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()

# Once we're happy, we can create a new flowset with just this data in it
NonDebris_FLOWSET <- cytoset_to_flowSet(gs_pop_get_data(Gates, "Non-Beads,Non-debris"))

# Lets look at each of the samples in the new flowset for how many events are in each
gs_pop_get_count_fast(Gates)


## ----event-length-ellipse---------------------------------
autoplot(NonDebris_FLOWSET, x = "Event_length", y = "Ir191Di", bins = 48) # Event_length only takes 48 distinct values in this data, 256 bins spread that thin and looked faded

# Damian's exact bounds (2026-08-05), Event_length centre nudged right 10 units per Damian's request.

mean_length <- c("Event_length" = 32, "Ir191Di" = 1225) # Event_length centre shifted right so xmin stays fixed at 7 while xmax rises

shape_length <- matrix(c(625, 0,
                         0, 1755625), ncol = 2, dimnames = list(c("Event_length", "Ir191Di"), c("Event_length", "Ir191Di"))) # Event_length semi-axis 20 -> 25 (25^2 = 625), xmin unchanged at 7, xmax raised 47 -> 57

R_length <- flowCore::ellipsoidGate(filterId = "event_length_singlets", .gate = shape_length, mean = mean_length)

if ("/Non-Beads,Non-debris/event_length_singlets" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "event_length_singlets") # remove any leftover gate from a previous run of this chunk before re-adding
gs_pop_add(Gates, R_length, parent = "Non-Beads,Non-debris", name = "event_length_singlets")
gs_get_pop_paths(Gates)
recompute(Gates)
gs_pop_get_count_fast(Gates)

ggcyto(Gates, aes(x = "Event_length", y = "Ir191Di"), subset = "Non-Beads,Non-debris") +
  geom_hex(bins = 48) + # matches Event_length's real 48 distinct values, 256 spread the same data too thin
  geom_gate("event_length_singlets", col = "blue", fill = "red") +
  geom_stats(adjust = c(1.5, 1.5), abs = TRUE) +
  coord_cartesian(xlim = c(0, 75), ylim = c(0, 6000)) # zoomed out to comfortably show the full population and the full ellipse on a plain linear scale, nothing clipped, no transform distortion

EventLengthSinglets_FLOWSET <- cytoset_to_flowSet(gs_pop_get_data(Gates, "event_length_singlets"))


## ----Compare gated to ungated, warning=FALSE--------------
# Preview Width and Residual, the parameters the next gate (doublet removal) will actually use, on the real
# population that gate starts from (it's built with parent = event_length_singlets). The event_length_singlets
# gate's own before/after is already shown above, not repeated here.
A1 <- autoplot(FLOWSET, x = "Width", y = "Residual", bins = 128) +
 scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()

A2 <- autoplot(EventLengthSinglets_FLOWSET, x = "Width", y = "Residual", bins = 128) +
 scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()

library(cowplot)
plot_grid(as.ggplot(A1), as.ggplot(A2), ncol = 2)


## ----plot polygon gate, warning=FALSE---------------------
#Our next gate will be a polygon gate to remove the doublets. We'll use Width and REsidual, the so-called Gaussian parameters to create
mat <- matrix(c(100,270,1000,1100,120,
                100,920,520,170,45)
, nrow = 5)

# Rename the new matrix with the correct parameter naems for the gate
colnames(mat) <-c("Width", "Residual")

# Create the gate
R2 <- polygonGate(mat)
if ("/Non-Beads,Non-debris/event_length_singlets/singlets1" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "singlets1") # remove any leftover gate from a previous run before re-adding
gs_pop_add(Gates, R2, parent = "event_length_singlets", name = "singlets1")
gs_get_pop_paths(Gates)
recompute(Gates)
gs_pop_get_count_fast(Gates)
# If you are ever unsure of your gating hierarchy you can always "plot()" the gating set to get a diagram
plot(Gates)
# Lets visualise the gat
autoplot(Gates, "singlets1", x = "Width", y = "Residual", bins = 128)+
  scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()
# Gate not quite the right shape so lets try again
gs_pop_remove(Gates, 'singlets1')

# Create matrix of co-ords to sketch in the gate
mat <- matrix(c(20,250,1000,1000,100,
                20,900,500,150,25)
, nrow = 5)

colnames(mat) <-c("Width", "Residual")

R2 <- polygonGate(mat)
if ("/Non-Beads,Non-debris/event_length_singlets/singlets1" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "singlets1") # remove any leftover gate from a previous run before re-adding
gs_pop_add(Gates, R2, parent = "event_length_singlets", name = "singlets1")
gs_get_pop_paths(Gates)
recompute(Gates)
gs_pop_get_count_fast(Gates)
plot(Gates)
autoplot(Gates, "singlets1", x = "Width", y = "Residual", bins = 128)+
   scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()


## ----plotting an ellipse gate, warning=FALSE--------------
library(ggcyto)
library(flowCore)

# Next singlet gate
autoplot(NonDebris_FLOWSET, x = "Ir191Di", y = "Ir193Di", bins = 256) +
  scale_y_flowCore_fasinh() +
  scale_x_flowCore_fasinh()

shape <- matrix(c(2045156,	3265186,
3265186,	5815469), ncol = 2, dimnames = list(c("Ir191Di", "Ir193Di"), c("Ir191Di", "Ir193Di"))) # whole original matrix scaled by 0.25 (each semi-axis halved: variance x0.25, covariance x0.25) so the shape and rotation are identical to before, just smaller, centre unchanged
mean <- c("Ir191Di"= 1570, "Ir193Di"=2500) # Ir191Di reverted back to 1570, Ir193Di down 500 (3000 -> 2500) per Damian, shape untouched

R3 <- flowCore::ellipsoidGate(filterId="singlets2",
.gate = shape, mean = mean)

if ("/Non-Beads,Non-debris/event_length_singlets/singlets1/singlets2" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "singlets2") # remove any leftover gate from a previous run before re-adding
gs_pop_add(Gates, R3, parent = "singlets1", name = "singlets2")
gs_get_pop_paths(Gates)
recompute(Gates)
gs_pop_get_count_fast(Gates)

ggcyto(Gates, aes("191", "193"), subset = "singlets1") +
  geom_hex(bins = 256) +
  geom_gate("singlets2", col = "blue", fill = "red") +
  geom_stats(adjust = c(1.5, 1.5), abs = TRUE) +
  coord_cartesian(xlim = c(0, 8000), ylim = c(0, 12000)) # linear scale, wide view: log10 was warping this tilted ellipse into two near-straight lines instead of a closed oval, same issue as the event_length ellipse

Singlets2_FLOWSET <- gs_pop_get_data(Gates, "singlets2")


## ----ellipse gate from flowClust, eval=FALSE--------------
# if(!require(flowClust)) BiocManager::install("flowClust")
# library(flowClust)
# 
# NonDebris_frame2 <- as(NonDebris_FLOWSET, "flowFrame")
# raw_vals2 <- exprs(NonDebris_frame2)[, c("Ir191Di", "Ir193Di")]
# centers_fit <- colMeans(raw_vals2)
# scales_fit <- apply(raw_vals2, 2, sd) # standardise before fitting, same reasoning as the event-length ellipse above
# 
# Scaled_frame2 <- NonDebris_frame2
# exprs(Scaled_frame2)[, c("Ir191Di", "Ir193Di")] <- scale(raw_vals2, center = centers_fit, scale = scales_fit)
# 
# fit <- flowClust(Scaled_frame2, varNames = c("Ir191Di", "Ir193Di"), K = 1, trans = 0)
# 
# mean_fit <- fit@mu[1, ] * scales_fit + centers_fit
# names(mean_fit) <- c("Ir191Di", "Ir193Di")
# 
# S_fit <- diag(scales_fit)
# shape_fit <- S_fit %*% fit@sigma[1, , ] %*% S_fit
# dimnames(shape_fit) <- list(c("Ir191Di", "Ir193Di"), c("Ir191Di", "Ir193Di"))
# 
# R3_fit <- flowCore::ellipsoidGate(filterId = "singlets2", .gate = shape_fit, mean = mean_fit, distance = qchisq(0.95, df = 2))


## ----Create Live Gate, warning=FALSE----------------------
autoplot(FLOWSET, x = "Time", y = "Pt195Di", bins = 128) +
  scale_y_logicle()

# Create gate 4 on Live cells
R4 <- rectangleGate(filterId="Non-Beads,Non-debris",
"Time"=c(0, 1500000), "Pt195Di"=c(0, 1000))

if ("/Non-Beads,Non-debris/event_length_singlets/singlets1/singlets2/LIVE" %in% gs_get_pop_paths(Gates)) gs_pop_remove(Gates, "LIVE") # remove any leftover gate from a previous run before re-adding
gs_pop_add(Gates, R4, parent = "singlets2", name = "LIVE")
gs_get_pop_paths(Gates)
recompute(Gates)
gs_pop_get_count_fast(Gates)

autoplot(Gates, "LIVE", bins = 128) +
  scale_y_logicle()

# Lets grab the data for the gated events; flowworkspace uses the cytoset rather than the flowSet...
LIVE_SINGLET_FLOWSET <- gs_pop_get_data(Gates, "LIVE")
# ... so we'll convert it to a flowSet ready to use for our downstream analyses
LIVE_SINGLET_FLOWSET <- cytoset_to_flowSet(LIVE_SINGLET_FLOWSET)

# Finally lets save the LIVE_SINGLET_FLOWSET to the RDS folder so that we can use it in the next chapters
saveRDS(LIVE_SINGLET_FLOWSET, here("Data","RDS", "LIVE_SINGLET_FLOWSET.rds"))


## ----time-cutoff-too-short, eval=FALSE--------------------
# # A cutoff set at roughly half the true run length would silently discard the back half of every sample's live events
# R4_too_short <- rectangleGate(filterId = "Live_TooShort", "Time" = c(0, 750000), "Pt195Di" = c(0, 1000))


## ----time-cutoff-too-long, eval=FALSE---------------------
# # A cutoff set well past where acquisition actually stopped would keep in whatever came after real cell data ended
# R4_too_long <- rectangleGate(filterId = "Live_TooLong", "Time" = c(0, 3000000), "Pt195Di" = c(0, 1000))


## ----Create Gating table, warning=FALSE-------------------
# Now we can create a table of the gating hierarchy, showing how many cells
ALL_cell_numbers <- fsApply(FLOWSET, nrow)
NonDebris_cell_numbers <- fsApply(NonDebris_FLOWSET, nrow)
Singlets_cell_numbers <- fsApply(Singlets2_FLOWSET, nrow)
LSF_cell_numbers <- fsApply(LIVE_SINGLET_FLOWSET, nrow)

# Combine all of these into a data frame
Gating_table <- data.frame(ALL = ALL_cell_numbers, ND = NonDebris_cell_numbers, Singlets = Singlets_cell_numbers, LIVE_SINGLET = LSF_cell_numbers)

Gating_table


## ----Save the LIVE_SINGLET_FLOWSET, warning=FALSE---------
saveRDS(LIVE_SINGLET_FLOWSET, here("Data","RDS", "LIVE_SINGLET_FLOWSET.rds"))


## ----Save the LIVE_SINGLET_FLOWSET to FCS, warning=FALSE----
dir.create(here("Data","fcs", "3_fcs-files_Live Singlets_R-Gated"), recursive = TRUE, showWarnings = FALSE)

write.flowSet(LIVE_SINGLET_FLOWSET, here("Data","fcs", "3_fcs-files_Live Singlets_R-Gated"))

