# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 08-Data-Cleaning-2-Channel-Names.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-channels-------------------------------
library(flowCore)
library(here)
if(!require(premessa)) devtools::install_github("ParkerICI/premessa")


## ----launch-premessa, eval=FALSE--------------------------
# premessa::paneleditor_GUI()


## ----list-files-------------------------------------------
here::here() # check we're in the right folder
list.files(here::here("Data", "fcs", "pruned")) # list cleaned fcs files
list.files(here::here("Data", "other")) # list any peripheral/supporting files


## ----load-renamed-----------------------------------------
RENAMED_FLOWSET <- read.flowSet(path = here::here("Data", "fcs", "pruned"), pattern = "\\.fcs$")


## ----save-renamed-----------------------------------------
saveRDS(RENAMED_FLOWSET, here::here("Data", "RDS", "RENAMED_FLOWSET.rds"))


## ----check-saved-renamed----------------------------------
file.exists(here::here("Data", "RDS", "RENAMED_FLOWSET.rds"))


## ----load-metadata-for-names------------------------------
library(readxl)
metadata <- read_xlsx(here::here("Data", "other", "ACDwR_metadata.xlsx"))
metadata


## ----rename-samples---------------------------------------
sampleNames(RENAMED_FLOWSET) # check the current order
metadata$file_name # confirm this lists the same files in the same order as above

sampleNames(RENAMED_FLOWSET) <- metadata$sample_id
sampleNames(RENAMED_FLOWSET)
saveRDS(RENAMED_FLOWSET, here::here("Data", "RDS", "RENAMED_FLOWSET.rds"))


## ----reorder-samples--------------------------------------
RENAMED_FLOWSET <- readRDS(here::here("Data", "RDS", "RENAMED_FLOWSET.rds"))
sampleNames(RENAMED_FLOWSET)

Reordered_RENAMED_FLOWSET <- RENAMED_FLOWSET[c(1, 3, 5, 2, 4)] # example order, replace with whatever order makes sense for your own data
sampleNames(Reordered_RENAMED_FLOWSET)

pData(Reordered_RENAMED_FLOWSET)$name <- sampleNames(Reordered_RENAMED_FLOWSET) # ggcyto uses pData()$name for graph labels, so we update it to match

saveRDS(Reordered_RENAMED_FLOWSET, file = here::here("Data", "RDS", "Reordered_RENAMED_FLOWSET.rds"))


## ----load-panel-------------------------------------------
panel <- read.csv(here::here("Data", "other", "ACDwR_panel.csv"))
head(panel)


## ----build-desc-------------------------------------------
panel$desc <- paste(panel$fcs_colname, panel$antigen, sep = "_")

# Time and Event_length aren't markers. They're the two channels the panel marks as marker_class "none",
# so leave their names exactly as they are. This matters beyond tidiness: flowCut identifies the time
# channel by name in the next chapter, and a channel called "Time_Time" isn't one it recognises.
panel$desc[panel$marker_class == "none"] <- panel$fcs_colname[panel$marker_class == "none"]


## ----check-panel-match------------------------------------
all(panel$fcs_colname == colnames(Reordered_RENAMED_FLOWSET))


## ----apply-desc-------------------------------------------
colnames(Reordered_RENAMED_FLOWSET) <- panel$desc
colnames(Reordered_RENAMED_FLOWSET)
saveRDS(Reordered_RENAMED_FLOWSET, file = here::here("Data", "RDS", "Reordered_RENAMED_FLOWSET.rds"))


## ----ggpairs-nxn, warning=FALSE---------------------------
library(GGally)
EXPRS_DF <- as.data.frame(
  exprs(Reordered_RENAMED_FLOWSET[[1]])
)

hex_panel <- function(data, mapping, ...) {
  ggplot(data, mapping) +
    geom_hex(bins = 30)
}

marker_cols <- setdiff(colnames(EXPRS_DF), c("Time", "Event_length")) # the 37 real markers; drops the two channels that aren't markers

NXN_GRID <- ggpairs(
  EXPRS_DF[, marker_cols],
  lower = list(continuous = hex_panel)
)

NXN_GRID


## ----save-ggpairs-nxn, warning=FALSE----------------------
library(cowplot)

ggsave2(
  here::here("Figures", "channel_check_NxN.pdf"),
  plot = NXN_GRID,
  width = 50,
  height = 50,
  limitsize = FALSE
)


## ----save-nxn-object--------------------------------------
saveRDS(NXN_GRID, here::here("Data", "RDS", "NXN_GRID.rds"))


## ----nxn-fallback, eval=FALSE-----------------------------
# library(ggplot2)
# library(gridExtra)
# 
# EXPRS_DF <- as.data.frame(exprs(Reordered_RENAMED_FLOWSET[[1]]))
# markers <- colnames(EXPRS_DF)
# 
# plot_list <- list()
# counter <- 1
# for (i in markers) {
#   for (j in markers) {
#     if (i != j) {
#       plot_list[[counter]] <- ggplot(EXPRS_DF, aes(x = .data[[i]], y = .data[[j]])) +
#         geom_point(alpha = 0.5) +
#         theme_minimal() +
#         labs(title = paste(i, "vs", j), x = i, y = j)
#       counter <- counter + 1
#     }
#   }
# }
# 
# do.call(grid.arrange, c(plot_list, ncol = length(markers) - 1))


## ----save-nxn-fallback, eval=FALSE------------------------
# library(cowplot)
# 
# NXN_FALLBACK <- do.call(arrangeGrob, c(plot_list, ncol = length(markers) - 1))
# 
# ggsave2(
#   here::here("Figures", "channel_check_NxN_fallback.pdf"),
#   plot = NXN_FALLBACK,
#   width = 50,
#   height = 50,
#   limitsize = FALSE
# )


## ----export-renamed-fcs, eval=FALSE-----------------------
# write.flowSet(Reordered_RENAMED_FLOWSET, here::here("Data", "renamed"))

