# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 09-Data-Cleaning-3-Acquisition-Anomalies.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-cleaning-------------------------------
library(here)
library(flowCore)
if(!require(PeacoQC)) BiocManager::install("PeacoQC")
library(PeacoQC)


## ----load-renamed-flowset---------------------------------
Reordered_RENAMED_FLOWSET <- readRDS(here("Data", "RDS", "Reordered_RENAMED_FLOWSET.rds"))


## ----peacoqc-cleaning, warning=FALSE, message=FALSE-------
channels_to_check <- colnames(Reordered_RENAMED_FLOWSET)[
  !colnames(Reordered_RENAMED_FLOWSET) %in% c("Time", "Event_length")
]

CLEANED_FLOWSET <- fsApply(Reordered_RENAMED_FLOWSET, function(x) {
  PeacoQC(
    ff               = x,
    channels         = channels_to_check,
    plot             = TRUE,
    save_fcs         = FALSE,
    output_directory = here("Outputs", "PeacoQC")
  )$FinalFF
})


## ----save-cleaned-----------------------------------------
sampleNames(CLEANED_FLOWSET) <- sampleNames(Reordered_RENAMED_FLOWSET)
pData(CLEANED_FLOWSET)$name <- sampleNames(CLEANED_FLOWSET)

saveRDS(CLEANED_FLOWSET, here("Data", "RDS", "CLEANED_FLOWSET.rds"))


## ----check-saved-cleaned----------------------------------
file.exists(here("Data", "RDS", "CLEANED_FLOWSET.rds"))


## ----compare-before-after, warning=FALSE------------------
library(cowplot)
library(ggcyto)

Reordered_RENAMED_FLOWSET <- readRDS(here("Data", "RDS", "Reordered_RENAMED_FLOWSET.rds"))
CLEANED_FLOWSET <- readRDS(here("Data", "RDS", "CLEANED_FLOWSET.rds"))

# Pick any channel and any sample, adjust to whatever's relevant for your own data
BEFORE <- autoplot(Reordered_RENAMED_FLOWSET[[1]], "Time", "Sm149Di_CD34", bins = 256) +
  ggtitle("Before cleaning")

AFTER <- autoplot(CLEANED_FLOWSET[[1]], "Time", "Sm149Di_CD34", bins = 256) +
  ggtitle("After cleaning")

plot_grid(as.ggplot(BEFORE), as.ggplot(AFTER))

ggsave2(here("Figures", "PeacoQC_before_after.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "PeacoQC_before_after.png"), width = 11, height = 8.5)


## ----compare-counts, warning=FALSE------------------------
library(ggplot2)

BEFORE_COUNTS <- as.data.frame(fsApply(Reordered_RENAMED_FLOWSET, nrow))
colnames(BEFORE_COUNTS) <- "Events"
BEFORE_COUNTS <- tibble::rownames_to_column(BEFORE_COUNTS, "Sample")

AFTER_COUNTS <- as.data.frame(fsApply(CLEANED_FLOWSET, nrow))
colnames(AFTER_COUNTS) <- "Events"
AFTER_COUNTS <- tibble::rownames_to_column(AFTER_COUNTS, "Sample")

# Both panels must share a y axis, or ggplot scales each one to its own data
# and a large drop looks like a small one
Y_MAX <- max(BEFORE_COUNTS$Events)

p_before <- ggplot(BEFORE_COUNTS, aes(x = Sample, y = Events, fill = Sample)) +
  geom_bar(stat = "identity") +
  ggtitle("Before cleaning") +
  scale_y_continuous(labels = scales::comma, limits = c(0, Y_MAX)) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))

p_after <- ggplot(AFTER_COUNTS, aes(x = Sample, y = Events, fill = Sample)) +
  geom_bar(stat = "identity") +
  ggtitle("After cleaning") +
  scale_y_continuous(labels = scales::comma, limits = c(0, Y_MAX)) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))

plot_grid(p_before, p_after)

ggsave2(here("Figures", "cleaning_counts_before_after.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "cleaning_counts_before_after.png"), width = 11, height = 8.5)


## ----flowCut-cleaning, warning=FALSE, message=FALSE-------
if(!require(flowCut)) BiocManager::install("flowCut")
library(flowCut)

CLEANED <- fsApply(
  Reordered_RENAMED_FLOWSET,
  function(x) flowCut(
    x,
    Directory = here("Outputs", "flowCut")
  )
)


## ----rebuild-flowset--------------------------------------
files <- list()
for (x in 1:length(CLEANED)) {
  files <- append(files, list(CLEANED[[x]]$frame))
}

CLEANED_FLOWCUT <- flowSet(files)
sampleNames(CLEANED_FLOWCUT) <- sampleNames(Reordered_RENAMED_FLOWSET)
pData(CLEANED_FLOWCUT)$name <- sampleNames(CLEANED_FLOWCUT)

saveRDS(CLEANED_FLOWCUT, here("Data", "RDS", "CLEANED_FLOWCUT.rds"))


## ----compare-tools, warning=FALSE-------------------------
COMPARISON_COUNTS <- data.frame(
  Sample   = sampleNames(Reordered_RENAMED_FLOWSET),
  Before   = as.vector(fsApply(Reordered_RENAMED_FLOWSET, nrow)),
  PeacoQC  = as.vector(fsApply(CLEANED_FLOWSET, nrow)),
  flowCut  = as.vector(fsApply(CLEANED_FLOWCUT, nrow))
)

COMPARISON_COUNTS$PeacoQC_pct <- round(
  100 * (COMPARISON_COUNTS$Before - COMPARISON_COUNTS$PeacoQC) / COMPARISON_COUNTS$Before, 2
)
COMPARISON_COUNTS$flowCut_pct <- round(
  100 * (COMPARISON_COUNTS$Before - COMPARISON_COUNTS$flowCut) / COMPARISON_COUNTS$Before, 2
)

COMPARISON_COUNTS


## ----flowcut-alwaysclean, eval=FALSE----------------------
# CLEANED_AC <- fsApply(
#   Reordered_RENAMED_FLOWSET,
#   function(x) flowCut(
#     x,
#     Directory   = here("Outputs", "flowCut_AlwaysClean"),
#     AlwaysClean = TRUE
#   )
# )
# 
# before <- as.vector(fsApply(Reordered_RENAMED_FLOWSET, nrow))
# after  <- sapply(CLEANED_AC, function(x) nrow(x$frame))
# 
# data.frame(
#   file    = sampleNames(Reordered_RENAMED_FLOWSET),
#   before  = before,
#   after   = after,
#   removed = before - after,
#   percent = round(100 * (before - after) / before, 2)
# )

