# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 10-Downsampling.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-downsample-----------------------------
library(here)
library(flowCore)

CLEANED_FLOWSET <- readRDS(here("Data", "RDS", "CLEANED_FLOWSET.rds"))


## ----downsample-------------------------------------------
set.seed(1234)
Downsample_filter <- sampleFilter(size = 5000, filterId = "dsFilter")
DOWNSAMPLER <- flowCore::filter(CLEANED_FLOWSET, Downsample_filter)

DOWNSAMPLED_CLEANED_FLOWSET <- Subset(CLEANED_FLOWSET, DOWNSAMPLER)
sampleNames(DOWNSAMPLED_CLEANED_FLOWSET)


## ----check-downsample-counts------------------------------
fsApply(DOWNSAMPLED_CLEANED_FLOWSET, nrow)


## ----save-downsampled-------------------------------------
saveRDS(DOWNSAMPLED_CLEANED_FLOWSET, here("Data", "RDS", "DOWNSAMPLED_CLEANED_FLOWSET.rds"))


## ----check-saved-downsampled------------------------------
file.exists(here("Data", "RDS", "DOWNSAMPLED_CLEANED_FLOWSET.rds"))


## ----compare-counts, warning=FALSE------------------------
library(ggplot2)
library(cowplot)

BEFORE_COUNTS <- as.data.frame(fsApply(CLEANED_FLOWSET, nrow))
colnames(BEFORE_COUNTS) <- "Events"
BEFORE_COUNTS <- tibble::rownames_to_column(BEFORE_COUNTS, "Sample")

AFTER_COUNTS <- as.data.frame(fsApply(DOWNSAMPLED_CLEANED_FLOWSET, nrow))
colnames(AFTER_COUNTS) <- "Events"
AFTER_COUNTS <- tibble::rownames_to_column(AFTER_COUNTS, "Sample")

# Both panels must share a y axis, or ggplot scales each one to its own data
# and a large drop looks like a small one
Y_MAX <- max(BEFORE_COUNTS$Events)

p_before <- ggplot(BEFORE_COUNTS, aes(x = Sample, y = Events, fill = Sample)) +
  geom_bar(stat = "identity") +
  ggtitle("Before downsampling") +
  scale_y_continuous(labels = scales::comma, limits = c(0, Y_MAX)) +
  theme_bw() +
  theme(legend.position = "none")

p_after <- ggplot(AFTER_COUNTS, aes(x = Sample, y = Events, fill = Sample)) +
  geom_bar(stat = "identity") +
  ggtitle("After downsampling") +
  scale_y_continuous(labels = scales::comma, limits = c(0, Y_MAX)) +
  theme_bw() +
  theme(legend.position = "none")

plot_grid(p_before, p_after)

ggsave2(here("Figures", "downsampling_before_after.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "downsampling_before_after.png"), width = 11, height = 8.5)


## ----reorder-downsampled----------------------------------
Reordered_DOWNSAMPLED_CLEANED_FLOWSET <- DOWNSAMPLED_CLEANED_FLOWSET[c(1, 3, 5, 2, 4)] # example order, replace with your real order
pData(Reordered_DOWNSAMPLED_CLEANED_FLOWSET)$name <- sampleNames(Reordered_DOWNSAMPLED_CLEANED_FLOWSET)

saveRDS(Reordered_DOWNSAMPLED_CLEANED_FLOWSET, here("Data", "RDS", "Reordered_DOWNSAMPLED_CLEANED_FLOWSET.rds"))


## ----downsample-too-small, eval=FALSE---------------------
# set.seed(1234)
# Downsample_filter_small <- sampleFilter(size = 500, filterId = "dsFilterSmall")
# DOWNSAMPLER_SMALL <- flowCore::filter(CLEANED_FLOWSET, Downsample_filter_small)
# DOWNSAMPLED_SMALL <- Subset(CLEANED_FLOWSET, DOWNSAMPLER_SMALL)

