# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 12-Extract-Expression-Data.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-extract--------------------------------
library(here)
library(flowCore)
library(readxl)
library(tidyr)

ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET <- readRDS(here("Data", "RDS", "ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET.rds"))
metadata <- read_xlsx(here("Data", "other", "ACDwR_metadata.xlsx"))
head(data.frame(metadata))


## ----extract-expression-----------------------------------
EXPRESSION_DATA <- fsApply(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET, exprs)
dim(EXPRESSION_DATA)
colnames(EXPRESSION_DATA)
saveRDS(EXPRESSION_DATA, here("Data", "RDS", "EXPRESSION_DATA.rds"))


## ----check-sample-order-----------------------------------
setequal(sampleNames(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET), metadata$sample_id)


## ----add-sample-ids---------------------------------------
sample_ids <- rep(sampleNames(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET),
                  fsApply(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET, nrow))
length(sample_ids) == nrow(EXPRESSION_DATA)


## ----build-expression-table-------------------------------
EXPRESSION_DATA_SAMPLE_ID <- data.frame(sample_id = sample_ids, EXPRESSION_DATA)
dim(EXPRESSION_DATA_SAMPLE_ID)
saveRDS(EXPRESSION_DATA_SAMPLE_ID, here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID.rds"))


## ----melt-and-add-condition-------------------------------
# Exclude the three columns that are not antigens: Time and Event_length come from the
# instrument, and Original_ID was added by PeacoQC in Chapter 9 to track event indices.
# Left in, they become "antigen" values and appear as facet panels in Chapter 13.
EXPRESSION_DATA_SAMPLE_ID_MELTED <- tidyr::pivot_longer(EXPRESSION_DATA_SAMPLE_ID,
  -c(sample_id, Time, Event_length, Original_ID),
  names_to = "antigen", values_to = "expression")

mm <- match(EXPRESSION_DATA_SAMPLE_ID_MELTED$sample_id, metadata$sample_id)
EXPRESSION_DATA_SAMPLE_ID_MELTED$condition <- metadata$condition[mm]

saveRDS(EXPRESSION_DATA_SAMPLE_ID_MELTED, here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID_MELTED.rds"))
head(EXPRESSION_DATA_SAMPLE_ID_MELTED)


## ----positional-join-demo---------------------------------
n_cells <- fsApply(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET, nrow)

labels_by_name     <- rep(sampleNames(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET), n_cells)
labels_by_position <- rep(metadata$sample_id, n_cells)

mean(labels_by_name != labels_by_position)


## ----positional-join-consequence--------------------------
CD34 <- fsApply(ARCSINH_DOWNSAMPLED_CLEANED_FLOWSET, exprs)[, "Sm149Di_CD34"]

condition_of <- function(ids) metadata$condition[match(ids, metadata$sample_id)]

conditions <- sort(unique(metadata$condition))
COMPARISON <- data.frame(
  condition   = conditions,
  by_name     = tapply(CD34, condition_of(labels_by_name),     median)[conditions],
  by_position = tapply(CD34, condition_of(labels_by_position), median)[conditions]
)
COMPARISON


## ----positional-join-plot---------------------------------
library(ggplot2)

ggplot(tidyr::pivot_longer(COMPARISON, -condition,
                           names_to = "labelling", values_to = "median_CD34"),
       aes(x = condition, y = median_CD34, fill = labelling)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(title = "The same cells, labelled two ways")

