# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 13-Data-Visualisation-Full.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-viz------------------------------------
library(here)
library(ggplot2)
library(ggridges)
library(cowplot)

EXPRESSION_DATA_SAMPLE_ID_MELTED <- readRDS(here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID_MELTED.rds"))


## ----density-all-markers, warning=FALSE, fig.width=11, fig.height=8.5----
ggplot(EXPRESSION_DATA_SAMPLE_ID_MELTED, aes(x = expression, color = sample_id)) +
  geom_density() +
  facet_wrap(~ antigen, scales = "free") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(size = 7), axis.text = element_text(size = 8),
    legend.title = element_blank())

ggsave2(here("Figures", "all_markers_density.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "all_markers_density.png"), width = 11, height = 8.5)


## ----ridge-all-markers, warning=FALSE, fig.width=11, fig.height=8.5----
ggplot(EXPRESSION_DATA_SAMPLE_ID_MELTED, aes(x = expression, y = condition)) +
  geom_density_ridges() +
  facet_wrap(~ antigen, scales = "free_x") +   # free_x, not free: y is `condition`, the same
                                               # five categories in every panel. Freeing y makes
                                               # ggplot repeat that whole list on all 40 facets,
                                               # which is wider than the panels themselves.
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(size = 7), axis.text = element_text(size = 8))

ggsave2(here("Figures", "all_markers_ridgeplot.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "all_markers_ridgeplot.png"), width = 11, height = 8.5)


## ----mfi-one-marker, warning=FALSE------------------------
library(dplyr)

MEDIAN_CD34 <- EXPRESSION_DATA_SAMPLE_ID_MELTED %>%
  filter(antigen == "Sm149Di_CD34") %>%
  group_by(sample_id, condition) %>%
  summarize(median_expression = median(expression), .groups = "drop")

ggplot(MEDIAN_CD34, aes(x = condition, y = median_expression, fill = condition)) +
  geom_col() +
  ylab("Median CD34 expression") +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))

ggsave2(here("Figures", "cd34_median_expression.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "cd34_median_expression.png"), width = 11, height = 8.5)


## ----mfi-second-marker, warning=FALSE---------------------
MEDIAN_CD38 <- EXPRESSION_DATA_SAMPLE_ID_MELTED %>%
  filter(antigen == "Yb172Di_CD38") %>%
  group_by(sample_id, condition) %>%
  summarize(median_expression = median(expression), .groups = "drop")

ggplot(MEDIAN_CD38, aes(x = condition, y = median_expression, fill = condition)) +
  geom_col() +
  ylab("Median CD38 expression") +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1))

ggsave2(here("Figures", "cd38_median_expression.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "cd38_median_expression.png"), width = 11, height = 8.5)


## ----build-palette----------------------------------------
source(here("Scripts", "palette.R"))

colour_conditions


## ----density-with-palette, warning=FALSE, fig.width=11, fig.height=8.5----
ggplot(EXPRESSION_DATA_SAMPLE_ID_MELTED, aes(x = expression, color = sample_id)) +
  geom_density() +
  facet_wrap(~ antigen, scales = "free") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(size = 7), axis.text = element_text(size = 8),
    legend.title = element_blank()) +
  custom_colour_manual()

