# ---------------------------------------------------------------------------
# BACKUP SCRIPT, generated from 14-Dimensionality-Reduction.Rmd
#
# This is not the script you are meant to write. Build your own as you read the
# chapter. Use this one when yours will not run: open both, find the line that
# differs, and fix yours.
#
# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.
# ---------------------------------------------------------------------------

## ----load-packages-dimred---------------------------------
library(here)
library(uwot)
library(Rtsne)
library(ggplot2)
library(cowplot)
library(dplyr)
library(viridis)
library(readxl)
library(dbscan)    # density clustering, used to gate regions in the Deep Dive
library(ggforce)   # geom_mark_hull(), draws those gates as outlines

source(here("Scripts", "palette.R"))   # colour_conditions and the custom_*_manual() helpers

EXPRESSION_DATA_SAMPLE_ID <- readRDS(here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID.rds"))
metadata <- read_xlsx(here("Data", "other", "ACDwR_metadata.xlsx"))


## ----select-marker-columns--------------------------------
panel <- read.csv(here("Data", "other", "ACDwR_panel.csv"))
panel_cols <- make.names(paste(panel$fcs_colname, panel$antigen, sep = "_"))

marker_cols <- panel_cols[panel$marker_class != "none"]
length(marker_cols)


## ----run-umap-all, warning=FALSE--------------------------
set.seed(1234)
EDU_umap <- umap(EXPRESSION_DATA_SAMPLE_ID[, marker_cols], n_neighbors = 15, metric = "cosine", min_dist = 0.001, verbose = TRUE)
EDU_umap <- as.data.frame(EDU_umap)
colnames(EDU_umap) <- c("UMAP1", "UMAP2")

EXPRESSION_DATA_SAMPLE_ID_UMAPPED <- cbind(EDU_umap, EXPRESSION_DATA_SAMPLE_ID)

# Bring the experimental condition across from the metadata sheet, joined on sample name
# rather than on position, the same rule as Chapter 12.
EXPRESSION_DATA_SAMPLE_ID_UMAPPED$condition <-
  metadata$condition[match(EXPRESSION_DATA_SAMPLE_ID_UMAPPED$sample_id, metadata$sample_id)]

saveRDS(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID_UMAPPED.rds"))


## ----umap-axis-limits-------------------------------------
xmin <- round(min(EXPRESSION_DATA_SAMPLE_ID_UMAPPED$UMAP1) - 1, 1)
xmax <- round(max(EXPRESSION_DATA_SAMPLE_ID_UMAPPED$UMAP1) + 1, 1)
ymin <- round(min(EXPRESSION_DATA_SAMPLE_ID_UMAPPED$UMAP2) - 1, 1)
ymax <- round(max(EXPRESSION_DATA_SAMPLE_ID_UMAPPED$UMAP2) + 1, 1)

c(xmin, xmax, ymin, ymax)


## ----plot-umap-all, warning=FALSE-------------------------
ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, aes(x = UMAP1, y = UMAP2, color = sample_id)) +
  geom_point(size = 0.5, alpha = 0.5) +
  xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 8, alpha = 1))) +
  theme_bw() +
  theme(legend.title = element_blank()) +
  ggtitle("UMAP, all markers, coloured by sample")

ggsave2(here("Figures", "umap_all_markers.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "umap_all_markers.png"), width = 11, height = 8.5)


## ----run-tsne-all, warning=FALSE--------------------------
tsne_in <- as.data.frame(EXPRESSION_DATA_SAMPLE_ID[, marker_cols])

set.seed(1234)
tsne_out <- Rtsne(tsne_in, pca = TRUE, verbose = TRUE, check_duplicates = FALSE)

EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE <- data.frame(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, tsne1 = tsne_out$Y[, 1], tsne2 = tsne_out$Y[, 2])

saveRDS(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE, here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE.rds"))


## ----plot-tsne-all, warning=FALSE-------------------------
ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE, aes(x = tsne1, y = tsne2, color = sample_id)) +
  geom_point(size = 0.5, alpha = 0.5) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 8, alpha = 1))) +
  theme_bw() +
  theme(legend.title = element_blank()) +
  ggtitle("tSNE, all markers, coloured by sample")

ggsave2(here("Figures", "tsne_all_markers.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "tsne_all_markers.png"), width = 11, height = 8.5)


## ----choose-lineage-markers-------------------------------
lineage_markers <- panel_cols[panel$marker_class == "type"]
length(lineage_markers)


## ----run-umap-lineage, warning=FALSE----------------------
set.seed(1234)
EDU_umap_lineage <- umap(EXPRESSION_DATA_SAMPLE_ID[, lineage_markers], n_neighbors = 15, metric = "cosine", min_dist = 0.001, verbose = TRUE)
EDU_umap_lineage <- as.data.frame(EDU_umap_lineage)
colnames(EDU_umap_lineage) <- c("UMAP1_lineage", "UMAP2_lineage")

EXPRESSION_DATA_SAMPLE_ID_UMAPPED_LINEAGE <- cbind(EDU_umap_lineage, EXPRESSION_DATA_SAMPLE_ID)
saveRDS(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_LINEAGE, here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID_UMAPPED_LINEAGE.rds"))


## ----plot-umap-lineage, warning=FALSE---------------------
ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_LINEAGE, aes(x = UMAP1_lineage, y = UMAP2_lineage, color = sample_id)) +
  geom_point(size = 0.5, alpha = 0.5) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 8, alpha = 1))) +
  theme_bw() +
  theme(legend.title = element_blank()) +
  ggtitle("UMAP, lineage markers only, coloured by sample")

ggsave2(here("Figures", "umap_lineage_markers.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "umap_lineage_markers.png"), width = 11, height = 8.5)


## ----run-tsne-lineage, warning=FALSE----------------------
tsne_in_lineage <- as.data.frame(EXPRESSION_DATA_SAMPLE_ID[, lineage_markers])

set.seed(1234)
tsne_out_lineage <- Rtsne(tsne_in_lineage, pca = TRUE, verbose = TRUE, check_duplicates = FALSE)

EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE_LINEAGE <- data.frame(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_LINEAGE, tsne1_lineage = tsne_out_lineage$Y[, 1], tsne2_lineage = tsne_out_lineage$Y[, 2])

saveRDS(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE_LINEAGE, here("Data", "RDS", "EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE_LINEAGE.rds"))


## ----plot-tsne-lineage, warning=FALSE---------------------
ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED_TSNE_LINEAGE, aes(x = tsne1_lineage, y = tsne2_lineage, color = sample_id)) +
  geom_point(size = 0.5, alpha = 0.5) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 8, alpha = 1))) +
  theme_bw() +
  theme(legend.title = element_blank()) +
  ggtitle("tSNE, lineage markers only, coloured by sample")

ggsave2(here("Figures", "tsne_lineage_markers.pdf"), width = 11, height = 8.5)
ggsave2(here("Figures", "tsne_lineage_markers.png"), width = 11, height = 8.5)


## ----umap-seed-stability, warning=FALSE-------------------
seed_plot <- function(s) {
  set.seed(s)
  u <- umap(EXPRESSION_DATA_SAMPLE_ID[, marker_cols], n_neighbors = 15,
            metric = "cosine", min_dist = 0.001, verbose = FALSE)
  d <- data.frame(UMAP1 = u[, 1], UMAP2 = u[, 2],
                  condition = EXPRESSION_DATA_SAMPLE_ID_UMAPPED$condition)
  ggplot(d, aes(x = UMAP1, y = UMAP2, colour = condition)) +
    geom_point(size = 0.01, alpha = 1/3) +
    custom_colour_manual() +
    theme_bw() + theme(legend.position = "none") +
    labs(title = paste0("set.seed(", s, ")"))
}

plot_grid(plotlist = lapply(c(1234, 42, 2026, 7), seed_plot), ncol = 4)


## ----umap-what-separates, warning=FALSE-------------------
by_protocol <- ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED,
                      aes(x = UMAP1, y = UMAP2, colour = condition)) +
  geom_point(size = 0.01, alpha = 1/2) +
  xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 6, alpha = 1))) +
  theme_bw() + theme(legend.title = element_blank(), legend.position = "bottom") +
  labs(title = "Coloured by fixation protocol")

by_marker <- ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED,
                    aes(x = UMAP1, y = UMAP2, colour = Sm149Di_CD34)) +
  geom_point(size = 0.01, alpha = 1/5) +
  xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
  viridis::scale_colour_viridis(option = "turbo") +
  theme_bw() + theme(legend.position = "bottom") +
  labs(title = "Coloured by CD34 expression", colour = NULL)

plot_grid(by_protocol, by_marker, ncol = 2)


## ----umap-every-marker, warning=FALSE---------------------
marker_plots <- list()
for (m in marker_cols) {
  marker_plots[[m]] <- ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED,
                              aes(x = UMAP1, y = UMAP2, colour = .data[[m]])) +
    geom_point(size = 0.01, alpha = 1/5) +
    xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
    viridis::scale_colour_viridis(option = "turbo") +
    theme_bw() +
    labs(title = m, colour = NULL) +
    theme(legend.key.size = unit(0.3, "cm"), legend.text = element_text(size = 6))
}

length(marker_plots)


## ----umap-marker-examples, warning=FALSE------------------
plot_grid(marker_plots[["Sm149Di_CD34"]], marker_plots[["Er168Di_CD71"]],
          marker_plots[["Dy161Di_CD90"]], marker_plots[["Nd143Di_CD45RA"]], ncol = 2)


## ----umap-every-marker-pdf, warning=FALSE-----------------
pages <- split(marker_plots, ceiling(seq_along(marker_plots) / 4))
page_grids <- lapply(pages, function(p) plot_grid(plotlist = p, ncol = 2))

gg_save_pdf <- function(plots, filename) {
  pdf(filename, width = 11, height = 8.5)
  for (p in plots) print(p)
  dev.off()
  invisible(NULL)
}

gg_save_pdf(page_grids, here("Figures", "umap_every_marker.pdf"))

length(page_grids)
file.exists(here("Figures", "umap_every_marker.pdf"))


## ----umap-perm-subset-------------------------------------
PERM <- c("2%PFA+NAS", "4%PFA+NAS", "8%PFA+NAS")
UMAP_PERM <- dplyr::filter(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, condition %in% PERM)

# Fixed limits have to come from the cells you are actually drawing. Step 2b's limits
# were taken from the whole projection, and the no-permeabilisation territory that sat
# on one side of it has just been filtered out, so reusing them here would reserve a
# third of the panel width for cells that are no longer in the plot.
perm_xmin <- round(min(UMAP_PERM$UMAP1) - 1, 1)
perm_xmax <- round(max(UMAP_PERM$UMAP1) + 1, 1)
perm_ymin <- round(min(UMAP_PERM$UMAP2) - 1, 1)
perm_ymax <- round(max(UMAP_PERM$UMAP2) + 1, 1)

nrow(UMAP_PERM)


## ----umap-marker-condition-check--------------------------
hi <- UMAP_PERM[UMAP_PERM$Er168Di_CD71 >= quantile(UMAP_PERM$Er168Di_CD71, 0.95), ]
table(hi$condition)


## ----umap-gate-regions, warning=FALSE---------------------
gate_regions <- function(data, marker, top = 0.05, eps = 0.6, minPts = 25) {
  v  <- data[[marker]]
  hi <- data[v >= quantile(v, 1 - top), c("UMAP1", "UMAP2")]
  if (nrow(hi) < minPts) return(hi[0, ])
  cl <- dbscan::dbscan(as.matrix(hi), eps = eps, minPts = minPts)
  hi$region <- cl$cluster
  hi[hi$region > 0, ]     # region 0 is dbscan's noise label
}

gate_plot <- function(marker) {
  g <- gate_regions(UMAP_PERM, marker)
  n <- if (nrow(g)) length(unique(g$region)) else 0
  p <- ggplot(UMAP_PERM, aes(x = UMAP1, y = UMAP2)) +
    geom_point(aes(colour = .data[[marker]]), size = 0.01, alpha = 1/5) +
    xlim(c(perm_xmin, perm_xmax)) + ylim(c(perm_ymin, perm_ymax)) +
    viridis::scale_colour_viridis(option = "turbo") +
    theme_bw() + theme(legend.position = "none")
  if (n > 0) {
    p <- p + geom_mark_hull(data = g, aes(group = factor(region)),
                            expand = unit(2, "mm"), radius = unit(2, "mm"),
                            colour = "black", linewidth = 0.4)
  }
  p + labs(title = sprintf("%s: %d region(s), cutoff %.2f",
                           marker, n, quantile(UMAP_PERM[[marker]], 1 - 0.05)))
}

plot_grid(gate_plot("Sm149Di_CD34"), gate_plot("Yb172Di_CD38"),
          gate_plot("Er168Di_CD71"), gate_plot("Dy161Di_CD90"), ncol = 2)


## ----umap-noperm-patches----------------------------------
NOPERM <- dplyr::filter(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, condition == "4%_PFA")

cl <- dbscan::dbscan(as.matrix(NOPERM[, c("UMAP1", "UMAP2")]), eps = 0.8, minPts = 30)
NOPERM$patch <- cl$cluster

NOPERM %>%
  dplyr::filter(patch > 0) %>%
  group_by(patch) %>%
  summarise(n = n(),
            x_from = round(min(UMAP1), 2), x_to = round(max(UMAP1), 2),
            y_from = round(min(UMAP2), 2), y_to = round(max(UMAP2), 2))


## ----umap-gate-manual, warning=FALSE----------------------
ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, aes(x = UMAP1, y = UMAP2)) +
  geom_point(aes(colour = condition), size = 0.01, alpha = 1/3) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 6, alpha = 1))) +
  annotate("rect", xmin = -11.7, xmax = -7.8, ymin = -10.0, ymax = 5.3,
           alpha = 0.2, fill = "blue", colour = "blue", linewidth = 0.5) +
  annotate("text", x = -9.7, y = 6.4, label = "No permeabilisation",
           colour = "blue", size = 3.5) +
  theme_bw() + theme(legend.title = element_blank(), legend.position = "bottom")


## ----umap-gate-purity-------------------------------------
gated <- EXPRESSION_DATA_SAMPLE_ID_UMAPPED %>%
  dplyr::filter(UMAP1 >= -12.2, UMAP1 <= -6.7, UMAP2 >= -9.6, UMAP2 <= 5.1)

table(gated$condition)


## ----umap-territories, warning=FALSE----------------------
EXPRESSION_DATA_SAMPLE_ID_UMAPPED$territory <- dplyr::case_when(
  EXPRESSION_DATA_SAMPLE_ID_UMAPPED$condition == "4%_PFA"            ~ "No permeabilisation",
  EXPRESSION_DATA_SAMPLE_ID_UMAPPED$condition == "4%PFA+1%GLUTA+NAS" ~ "Glutaraldehyde",
  TRUE                                                               ~ "PFA + NAS")

territory_cols <- c("No permeabilisation" = "#58508d",
                    "Glutaraldehyde"      = "#bc5090",
                    "PFA + NAS"           = "#ffa600")

# Split each territory into its own separate patches, for the same reason as before:
# a group scattered across the plot must not become one hull spanning all of it.
patches <- lapply(split(EXPRESSION_DATA_SAMPLE_ID_UMAPPED,
                        EXPRESSION_DATA_SAMPLE_ID_UMAPPED$territory), function(d) {
  cl <- dbscan::dbscan(as.matrix(d[, c("UMAP1", "UMAP2")]), eps = 0.8, minPts = 30)
  d$patch <- cl$cluster
  d[d$patch > 0, ]
})
PATCHES <- dplyr::bind_rows(patches)
PATCHES$grp <- paste(PATCHES$territory, PATCHES$patch)

# Label only the largest patch of each territory, so each name is drawn once
biggest <- PATCHES %>% count(territory, grp) %>%
  group_by(territory) %>% slice_max(n, n = 1) %>% pull(grp)
PATCHES$lab <- ifelse(PATCHES$grp %in% biggest, PATCHES$territory, NA_character_)

ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, aes(x = UMAP1, y = UMAP2)) +
  geom_point(size = 0.01, alpha = 1/6, colour = "grey40") +
  geom_mark_hull(data = PATCHES,
                 aes(group = grp, fill = territory, colour = territory, label = lab),
                 concavity = 2, expand = unit(2, "mm"), radius = unit(2, "mm"),
                 alpha = 0.18, linewidth = 0.4, label.fontsize = 9,
                 con.cap = unit(1, "mm")) +
  scale_fill_manual(values = territory_cols) +
  scale_colour_manual(values = territory_cols) +
  xlim(c(xmin - 4, xmax + 4)) + ylim(c(ymin - 2, ymax + 3)) +
  theme_bw() + theme(legend.position = "none") +
  labs(title = "What the projection separates on: fixation protocol")


## ----umap-by-condition, warning=FALSE---------------------
one_condition <- function(cond, colour) {
  EXPRESSION_DATA_SAMPLE_ID_UMAPPED %>%
    dplyr::filter(condition == cond) %>%
    ggplot(aes(x = UMAP1, y = UMAP2)) +
    geom_point(size = 0.01, alpha = 1/2, colour = colour) +
    xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
    theme_bw() + labs(title = cond)
}

conditions <- sort(unique(EXPRESSION_DATA_SAMPLE_ID_UMAPPED$condition))
condition_panels <- Map(one_condition, conditions, colour_conditions[seq_along(conditions)])

plot_grid(plotlist = c(condition_panels, list(by_protocol)), nrow = 2)


## ----umap-per-sample, warning=FALSE-----------------------
ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED,
       aes(x = UMAP1, y = UMAP2, colour = condition)) +
  geom_point(size = 0.05, alpha = 1/10) +
  xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
  custom_colour_manual() +
  facet_wrap(~ sample_id) +
  theme_bw() +
  theme(legend.position = "none")


## ----umap-per-sample-nested, eval=FALSE-------------------
# library(ggh4x)
# 
# ggplot(EXPRESSION_DATA_SAMPLE_ID_UMAPPED,
#        aes(x = UMAP1, y = UMAP2, colour = condition)) +
#   geom_point(size = 0.05, alpha = 1/10) +
#   xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
#   custom_colour_manual() +
#   facet_nested_wrap(~ condition + sample_id, ncol = 4) +
#   theme_bw() +
#   theme(legend.position = "none")


## ----umap-sample-frac-------------------------------------
set.seed(42)
UMAP_FRAC <- dplyr::sample_frac(EXPRESSION_DATA_SAMPLE_ID_UMAPPED, 0.05)
nrow(UMAP_FRAC)


## ----umap-composite, warning=FALSE------------------------
title <- ggdraw() +
  draw_label("What separates the cells in this projection?",
             fontface = "bold", x = 0, hjust = 0) +
  theme(plot.margin = margin(0, 0, 0, 7))

subtitle <- ggdraw() +
  draw_label("The same UMAP coloured by fixation protocol and by CD34 expression",
             fontface = "italic", x = 0, hjust = 0, size = 10) +
  theme(plot.margin = margin(0, 0, 0, 7))

caption <- ggdraw() +
  draw_label(
    "The five samples are one bone marrow prepared five ways. Protocol, not cell type, is what this projection separates on: the unpermeabilised sample sits apart because its intracellular markers were never stained, and the glutaraldehyde sample separates for its own reasons. The three PFA concentrations with NAS overlap, which is the practical result. Colour by every technical variable you have before you colour by the one you care about.",
    fontface = "italic", x = 0, hjust = 0, size = 8) +
  theme(plot.margin = margin(0, 0, 0, 7))

plot_grid(title, subtitle, plot_grid(by_protocol, by_marker, ncol = 2), caption,
          ncol = 1, rel_heights = c(0.1, 0.1, 1, 0.3))


## ----umap-animate, eval=FALSE-----------------------------
# library(gganimate)
# library(gifski)
# 
# anim_base <- ggplot(UMAP_FRAC, aes(x = UMAP1, y = UMAP2, colour = condition)) +
#   geom_point(size = 1, alpha = 1) +
#   xlim(c(xmin, xmax)) + ylim(c(ymin, ymax)) +
#   custom_colour_manual() +
#   guides(colour = guide_legend(override.aes = list(size = 6, alpha = 1))) +
#   theme_bw() +
#   theme(legend.title = element_blank())
# 
# # Cumulative: each condition is added to the ones already drawn
# anim_base +
#   transition_manual(condition, cumulative = TRUE) +
#   labs(title = "Condition: {current_frame}")
# 
# anim_save(here("Images", "umap_animation_cumulative.gif"))
# 
# # One at a time, fading between them
# anim_base +
#   transition_states(condition, transition_length = 2, state_length = 1) +
#   enter_fade() + exit_fade() +
#   labs(title = "Condition: {closest_state}")
# 
# anim_save(here("Images", "umap_animation_states.gif"))


## ----interactive-marker-choice, eval=FALSE----------------
# library(tcltk)
# 
# choose_markers <- tk_select.list(marker_cols, multiple = TRUE,
#                                  title = "Choose the markers to project on")
# saveRDS(choose_markers, file = here("Data", "RDS", "choose_markers.rds"))


## ----umap-chosen-markers, warning=FALSE-------------------
# Substitute your own choose_markers here. These four are the markers that produced
# real gates earlier in this chapter, so they are a defensible small set rather than
# an arbitrary one.
chosen_markers <- c("Sm149Di_CD34", "Yb172Di_CD38", "Er168Di_CD71", "Y89Di_CD41..")

set.seed(1234)
chosen_umap <- umap(EXPRESSION_DATA_SAMPLE_ID[, chosen_markers],
                    n_neighbors = 15, metric = "cosine", min_dist = 0.001,
                    verbose = FALSE)

CHOSEN <- data.frame(UMAP1 = chosen_umap[, 1], UMAP2 = chosen_umap[, 2],
                     condition = EXPRESSION_DATA_SAMPLE_ID_UMAPPED$condition)

chosen_plot <- ggplot(CHOSEN, aes(x = UMAP1, y = UMAP2, colour = condition)) +
  geom_point(size = 0.01, alpha = 1/3) +
  custom_colour_manual() +
  guides(colour = guide_legend(override.aes = list(size = 6, alpha = 1))) +
  theme_bw() + theme(legend.title = element_blank(), legend.position = "bottom") +
  labs(title = paste(length(chosen_markers), "chosen markers"))

plot_grid(by_protocol + labs(title = paste(length(marker_cols), "markers")),
          chosen_plot, ncol = 2)

