# make_backup_scripts.R
#
# Generates one plain .R script per chapter into Scripts/backup/, straight from the
# chapter .Rmd files. These are the reader's fallback: if their own script will not run,
# they compare it against the matching file here.
#
# WHY GENERATED AND NOT HAND-WRITTEN. A hand-maintained copy of every chapter's code is a
# second copy that drifts every time a chapter is edited, silently, with nothing checking
# that the pair still match. Generating them means a chapter edit is carried through by
# re-running this, and index.Rmd runs it at the start of every book build.
#
# Run by hand:  Rscript Scripts/make_backup_scripts.R
#
# NOTE on eval=FALSE chunks: knitr::purl() emits their bodies already commented out, so
# the deliberate-failure demos stay visible as text and the script still runs top to
# bottom. That is purl's own behaviour, not something done here.
#
# Added 2026-08-24, after an alpha tester was seen copying commands from the website
# straight into the console with nowhere to keep them.

book_root <- if (nzchar(Sys.getenv("ACDWR_ROOT"))) Sys.getenv("ACDWR_ROOT") else "."
out_dir   <- if (nzchar(Sys.getenv("ACDWR_OUT")))  Sys.getenv("ACDWR_OUT")  else file.path(book_root, "Scripts", "backup")

# Chapter list read from _bookdown.yml rather than hardcoded, so adding a chapter to the
# book adds it here with no second edit to remember.
cfg   <- yaml::read_yaml(file.path(book_root, "_bookdown.yml"))
chaps <- setdiff(cfg$rmd_files, "index.Rmd")

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# Drop whole chunks whose only content is a knitr::include_graphics() call. These are the
# screenshot chunks, 14 of them in Chapter 2 alone: figures in the book, noise in a
# script. Blocks are split on purl's own "## ----name----" headers.
strip_image_chunks <- function(lines) {
  starts <- grep("^## ----", lines)
  if (!length(starts)) return(lines)
  ends <- c(starts[-1] - 1L, length(lines))
  keep <- rep(TRUE, length(lines))
  for (i in seq_along(starts)) {
    body <- lines[(starts[i] + 1L):ends[i]]
    body <- body[nzchar(trimws(body))]
    if (length(body) && all(grepl("include_graphics", body, fixed = TRUE))) {
      keep[starts[i]:ends[i]] <- FALSE
    }
  }
  lines[keep]
}

# A chapter with almost no code produces a file that is header and nothing else, which is
# worse than no file: a reader opens it expecting help. Content is counted rather than
# UNCOMMENTED content, because Chapter 3's install chunks are all eval=FALSE and therefore
# arrive commented out while still being the whole substance of that chapter.
# Chapter 1 is the only one this drops: it purls to a single commented example line.
has_enough_content <- function(lines) {
  content <- lines[nzchar(trimws(lines)) & !grepl("^## ----", lines)]
  length(content) >= 5
}

header <- function(chapter_file) c(
  "# ---------------------------------------------------------------------------",
  paste0("# BACKUP SCRIPT, generated from ", chapter_file),
  "#",
  "# This is not the script you are meant to write. Build your own as you read the",
  "# chapter. Use this one when yours will not run: open both, find the line that",
  "# differs, and fix yours.",
  "#",
  "# Generated by Scripts/make_backup_scripts.R. Edits here are overwritten.",
  "# ---------------------------------------------------------------------------",
  ""
)

written <- 0L
for (ch in chaps) {
  target <- file.path(out_dir, sub("[.]Rmd$", ".R", ch))
  knitr::purl(file.path(book_root, ch), output = target, documentation = 1, quiet = TRUE)
  lines <- strip_image_chunks(readLines(target, warn = FALSE))
  if (!has_enough_content(lines)) {
    unlink(target)
    cat(sprintf("%-45s skipped, no runnable code\n", basename(target)))
    next
  }
  writeLines(c(header(ch), lines), target)
  written <- written + 1L
  cat(sprintf("%-45s %4d lines\n", basename(target), length(lines) + 10L))
}

cat(sprintf("\n%d backup scripts written to %s\n", written, normalizePath(out_dir)))
